#! /bin/sh

# bash ~/change_to_dvorak.sh

pgrep -x sxhkd > /dev/null || sxhkd -m -1 &

~/.config/polybar/launch.sh &
picom &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window borders
bspc config border_width 4       # width in pixels
bspc config window_gap 10        # gap between windows
# bspc config focused_border_color "#ff5555"   # color of focused window
bspc config focused_border_color "#ffffff"   # color of focused window
bspc config normal_border_color  "#44475a"   # color of unfocused windows

bspc rule -a Gimp desktop='^9' follow=on
bspc rule -a zen desktop='^1' follow=on
bspc rule -a vlc desktop='^10' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a opengl state=floating 
bspc rule -a initial_term_three desktop=^3 
bspc rule -a initial_term_eight desktop=^8 
bspc rule -a ttyclock desktop=^10 state=floating rectangle=420x260+1320+400
bspc rule -a cava_init desktop=^10 state=floating rectangle=1870x260+20+790
bspc rule -a cmatrix_init desktop=^10 state=floating rectangle=380x400+1200+150
bspc rule -a feh:feh -o title=feh-rice desktop='^10' state=floating rectangle=240x300+900+350 

# Kitty
kitty --class initial_term_three &
kitty --class initial_term_eight &
kitty --class ttyclock sh -c "tty-clock -c -t; exec zsh" &
kitty --class cmatrix_init sh -c "cmatrix; exec zsh" &
kitty --class cava_init sh -c "cava; exec zsh" &

# feh
feh --bg-scale ~/.config/wallpapers/l_lawliet.png &
feh --zoom fill --scale-down --title "feh-rice" --no-menus --borderless ~/.config/wallpapers/itachi.jpg &

# Friday workspace routing
bspc rule -a kitty:friday-term desktop='^3'
bspc rule -a kitty:friday-nvim desktop='^8'

zen-browser &
